### PR TITLE
story/TYTA-124/create-reset-password-feature

### PR DESCRIPTION
**Pull request by remirubis**
### Description

Created functionality to allow users to reset their password by receiving a link in an email.

### CODE REVIEW

**Review by FabienHP — DISMISSED** [review]
LGTM

**Review by kilianpichard — COMMENTED** [review]
General question : Do we really need to stock tokens in database ? Check out this code i does for a project, i generated a jwtoken with user id in it and check if it was valid in the second function (we can add a 2h lifetime for exemple)

`async function sendResetEmail(user) {
    try {
        let existing = await User.find({username: user.username});

        if (existing.length == 0) {
            throw new Error('User not found');
        } else {
            let token = await jwt.sign({sub: existing[0]._id}, secret, {});

            console.log('tok'+ token);
            let email = nodemailer.createTransport({
                service: 'gmail',
                auth: {
                    user: 'xxx',
                    pass: 'xxx'
                },
                tls: {
                    rejectUnauthorized: false
                }
            });

            let newUser = await User.findOneAndUpdate({username: user.username}, {resetToken: token})

            let from = `XXX <i***@gmail.com>`
            let mailOptions = {
                from: from,
                to: user.username,
                subject: 'Reset Password',
                html: 'Click on the link to reset your password: <br>' + 'http://localhost:8080/reset-password/'+existing[0]._id+'/'+token
            }

            email.sendMail(mailOptions, function (err,info) {
                if (err) {
                    throw err;
                }
            });

            return {
                ...user,
                _id: newUser._id,
                resetToken: token
            };
        }
    } catch (error) {

        return error;
    }
}

async function resetPassword(data) {

    try {
        let existing = await User.find({_id: data.id});
        if (existing.length == 0) {
            throw new Error('User not found');
        } else {
            if(existing[0].resetToken == data.token){
                let token = await jwt.verify(data.token, secret);
                if (token.sub == existing[0]._id) {
                    let hash = bcrypt.hashSync(data.password, saltRounds);
                    let user = await User.findOneAndUpdate({_id: data.id}, {password: hash, resetToken: null});
                    user = await User.findOne({_id: data.id});
                    return user;

            }else{
                    throw new Error('Invalid token');
            }
            } else {
                throw new Error('Invalid Token');
            }
        }
    } catch (error) {
        return error;
    }
}
`

**Comment by kilianpichard** [comment]
And maybe rename resetPassword router to auth router to add login/lougout after

**Comment by remirubis** [comment]
> General question : Do we really need to stock tokens in database ? Check out this code i does for a project, i generated a jwtoken with user id in it and check if it was valid in the second function (we can add a 2h lifetime for exemple)
> 
> 
> 
> `async function sendResetEmail(user) {
> 
>     try {
> 
>         let existing = await User.find({username: user.username});
> 
> 
> 
>         if (existing.length == 0) {
> 
>             throw new Error('User not found');
> 
>         } else {
> 
>             let token = await jwt.sign({sub: existing[0]._id}, secret, {});
> 
> 
> 
>             console.log('tok'+ token);
> 
>             let email = nodemailer.createTransport({
> 
>                 service: 'gmail',
> 
>                 auth: {
> 
>                     user: 'xxx',
> 
>                     pass: 'xxx'
> 
>                 },
> 
>                 tls: {
> 
>                     rejectUnauthorized: false
> 
>                 }
> 
>             });
> 
> 
> 
>             let newUser = await User.findOneAndUpdate({username: user.username}, {resetToken: token})
> 
> 
> 
>             let from = `XXX <i***@gmail.com>`
> 
>             let mailOptions = {
> 
>                 from: from,
> 
>                 to: user.username,
> 
>                 subject: 'Reset Password',
> 
>                 html: 'Click on the link to reset your password: <br>' + 'http://localhost:8080/reset-password/'+existing[0]._id+'/'+token
> 
>             }
> 
> 
> 
>             email.sendMail(mailOptions, function (err,info) {
> 
>                 if (err) {
> 
>                     throw err;
> 
>                 }
> 
>             });
> 
> 
> 
>             return {
> 
>                 ...user,
> 
>                 _id: newUser._id,
> 
>                 resetToken: token
> 
>             };
> 
>         }
> 
>     } catch (error) {
> 
> 
> 
>         return error;
> 
>     }
> 
> }
> 
> 
> 
> async function resetPassword(data) {
> 
> 
> 
>     try {
> 
>         let existing = await User.find({_id: data.id});
> 
>         if (existing.length == 0) {
> 
>             throw new Error('User not found');
> 
>         } else {
> 
>             if(existing[0].resetToken == data.token){
> 
>                 let token = await jwt.verify(data.token, secret);
> 
>                 if (token.sub == existing[0]._id) {
> 
>                     let hash = bcrypt.hashSync(data.password, saltRounds);
> 
>                     let user = await User.findOneAndUpdate({_id: data.id}, {password: hash, resetToken: null});
> 
>                     user = await User.findOne({_id: data.id});
> 
>                     return user;
> 
> 
> 
>             }else{
> 
>                     throw new Error('Invalid token');
> 
>             }
> 
>             } else {
> 
>                 throw new Error('Invalid Token');
> 
>             }
> 
>         }
> 
>     } catch (error) {
> 
>         return error;
> 
>     }
> 
> }
> 
> `

@kilianpichard I see informations about good practices to reset password online and some content suggest crypt instead of jwt https://security.stackexchange.com/questions/213975/how-to-properly-create-a-password-reset-token

But I don't know what's the best thing to be honest

**Review by FabienHP — APPROVED** [review]
LGTM

**Pull request merged**
